// <auto-generated />
using System;
using Crawler.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crawler.Migrations
{
    [DbContext(typeof(CrawlerContext))]
    partial class CrawlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Crawler.Domain.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("Crawler.Domain.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Assunto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Distribuição")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relator")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("Crawler.Domain.SitProcesso", b =>
                {
                    b.Property<int>("SitProcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroProcesso")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Situacao")
                        .HasColumnType("TEXT");

                    b.HasKey("SitProcessoId");

                    b.HasIndex("ProcessoId");

                    b.ToTable("SitProcessos");
                });

            modelBuilder.Entity("Crawler.Domain.Movimentacao", b =>
                {
                    b.HasOne("Crawler.Domain.Processo", "Processo")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("Crawler.Domain.SitProcesso", b =>
                {
                    b.HasOne("Crawler.Domain.Processo", "Processo")
                        .WithMany("SitProcessos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("Crawler.Domain.Processo", b =>
                {
                    b.Navigation("Movimentacoes");

                    b.Navigation("SitProcessos");
                });
#pragma warning restore 612, 618
        }
    }
}
